#!/bin/bash

savePath='/home/asfs/Kwon'
logPath='/home/asfs/Kwon'

today=`date +%Y%m%d%`
Date=`date +%Y%m%d -d '-1days'`
startTime=$(date +%s%N)
kisa_num_list=(01093174965 01046321221 01071474451)

echo "[ MDN ]      [ HAM ]   [ SPAM ]" >> $savePath/msg_count_$Date.log
for kisaNum in "${kisa_num_list[@]}"
do
#hamCnt=`grep -r $kisaNum $logPath/$Date/* | cut -d '|' -f 10 | sort | uniq -c | head -1 | awk '$2 ~ /0x01/{print $1}'`
#spamCnt=`grep -r $kisaNum $logPath/$Date/* | cut -d '|' -f 10 | sort | uniq -c | tail -1 | awk '$2 ~ /0x03/{print $1}'`
hamCnt=`grep -r $kisaNum $logPath/test_log_0213.txt | cut -d '|' -f 10 | sort | uniq -c | awk '$2 ~ /0x01/{print $1}'`
spamCnt=`grep -r $kisaNum $logPath/test_log_0213.txt | cut -d '|' -f 10 | sort | uniq -c | awk '$2 ~ /0x03/{print $1}'`

	echo "$kisaNum		$hamCnt		$spamCnt" >> $savePath/msg_count_$Date.log	
done
duration=$((($(date +%s%N) - $startTime)/1000000))
Hour=$(($duration/3600000 ))
Min=$(($(($duration%3600000))/60000))
Sec=$(($(($duration%60000))/1000))
Msec=$(($duration%1000))
len=$((${#Msec}))
if [ $len -lt 3 ]
then
Msec=0$Msec
fi
echo "[ time(duration) : $Hour(h)  $Min(m)  $Sec.$Msec(s) ]" >> $savePath/msg_count_$Date.log

