
CREATE TABLE TH_SFS_APP_VER_HIST (
  VM_VERSION VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	OS_TYPE VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	SAVE_DT VARCHAR2(14 BYTE) NOT NULL ENABLE, 
	USED_FLAG VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	VM_INFO VARCHAR2(128 BYTE), 
	ETC VARCHAR2(128 BYTE),
  CONSTRAINT TH_SFS_APP_VER_HIST_PK PRIMARY KEY (VM_VERSION,OS_TYPE)
);
